[package]
name = "xkbcommon"
version = "0.4.0"
authors = ["Remi THEBAULT <remi.thebault@gmail.com>"]
description = "Rust bindings and wrappers for libxkbcommon"
repository = "https://github.com/rtbo/xkbcommon-rs"
readme = "README.md"
documentation = "https://rtbo.github.io/xkbcommon-rs/xkbcommon"
keywords = ["keyboard", "x11", "wayland", "xcb", "input"]
license = "MIT"

[dependencies]
libc = "0.2.99"
memmap = { version = "0.7.0", optional = true }
xcb = { version = "0.9.0", features = ["xkb"], optional = true }

[dev-dependencies]
evdev = "0.11.0"

[features]
x11 = ["xcb"]
wayland = ["memmap"]
