[package]
name = "xkbcommon"
version = "0.4.0"
authors = ["Remi THEBAULT <remi.thebault@gmail.com>"]
description = "Rust bindings and wrappers for libxkbcommon"
repository = "https://github.com/rtbo/xkbcommon-rs"
readme = "README.md"
documentation = "https://rtbo.github.io/xkbcommon-rs/xkbcommon"
keywords = ["keyboard", "x11", "wayland", "xcb", "input"]
license = "MIT"

[dependencies]
libc = "0.2"
memmap = { version = "0.7", optional=true }
xcb = { version = "0.8", features = ["xkb"], optional=true }

[features]
x11 = ["xcb"]
wayland = ["memmap"]
